### ISSUE TITLE
scrubber head not moving with mouse

### ISSUE THREAD

**Issue by ezio416** [nicoell/tm-editor-route#5]
This is just in the repo, not released yet, but the position of the head is not accounting for my UI scale

https://github.com/nicoell/tm-editor-route/assets/37951898/f69b3ec9-739e-4bba-ad53-f8deefffc2fb

**Comment by nicoell** [comment]
Thanks for the report. I found a more general issue with the Scrubber Head/Slider Grab that I fixed here: https://github.com/nicoell/tm-editor-route/commit/397e8ec23845af298aab8a290fb1eaf4932d790e

I quickly ramped up imgui's Global UI Scale and could not replicate your issue anymore. 
If you still have this issue with the latest update, please give me some info which kind of UI scale you are using. Thanks :)

**Comment by ezio416** [comment]
I pulled the latest changes, reloaded, and the issue is still present. I'm using 1.5x scale

**Comment by nicoell** [comment]
Thanks for checking. I'll look into it for the next update then.
